### ISSUE TITLE
Cannot install Starcounter on Win Server 2012 R2

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#204]
When trying to install Starcounter 2.3.1.6981 on Windows Server 2012 R2 in "Production" mode, following exception occurs:

![win server2012 copy](https://user-images.githubusercontent.com/4943949/29359699-fecb5f86-827f-11e7-8f39-fb5d0a8b8051.jpg)

Steps:
* Run installer
* Choose "Production" at the beginning
* Error when it tries to run service
* As it's part of installation procedure, the whole installation is rolled back
* Empty folder is left

cc @alemoi @andwah

**Comment by alemoi** [comment]
Simple question, what error do you see in the server log?

**Comment by mmnosek** [comment]
@alemoi which log do you mean?

**Comment by alemoi** [comment]
Server log `starcounter.0000000000.log` in server directory.

**Comment by mmnosek** [comment]
But is it still there if the installation is rolled back and it leaves only empty folder?

**Comment by miyconst** [comment]
Are the 8080 and 8181 ports available?

**Comment by mmnosek** [comment]
8080 is not available, but another (available) port has been chosen at the beginning of the installation.

**Comment by miyconst** [comment]
So, this could be due to the ports, and not related to the Win 2012 R2, should be checked.

**Comment by alemoi** [comment]
The personal server folder is not removed on uninstall. Please check there for the log.

**Comment by ubbeK** [comment]
> 8080 is not available, but another (available) port has been chosen at the beginning of the installation.

> So, this could be due to the ports, and not related to the Win 2012 R2, should be checked.

Is still an issue? @mmnosek

**Comment by mmnosek** [comment]
I don't have an access to the server where the problem occurred, unfortunately, but I think it's still important. Do you think that trying to install Starcounter when port 8080 is blocked should help to reproduce?

**Comment by ubbeK** [comment]
> Do you think that trying to install Starcounter when port 8080 is blocked should help to reproduce?

It would be nice to know if it does.

**Comment by mmnosek** [comment]
Ok, now I see what is the problem. Whole installation flow is a little bit tricky. We have 4 paths of installation:

1. Developer
2. Developer with additional settings
3. Production
4. Production with additional settings

Port 8080 or 8181 is already used. If I choose path 1 or 3, then availability is not checked. Whole installation procedure goes fine and at the end, there is an error as above. Installation is rolled back automatically. *User doesn't know what went wrong. Alert is not understandable*.

If I choose path 2 or 4, then I cannot install as long as I don't choose ports that are available. 

I think we should, first of all, add proper check and alert in path 1 or 3. Can we do this? :)

**Comment by ubbeK** [comment]
> I think we should, first of all, add proper check and alert in path 1 or 3. Can we do this? :)

I guess it should be possible. But what is occupying 8080/8181 ports? It there already is a Starcounter version installed, doesn't the installer go through the upgrade/downgrade process which doesn't have the settings page.

**Comment by mmnosek** [comment]
No, it's not because Starcounter is installed and running. It's just because a port is not available (I run file server on 8080 and then on 8181 just to make ports unavailable). It may happen that another server is using the port and we should deal with this.

**Comment by ubbeK** [comment]
Ok, thanks for the investigation. I am not quiet sure in what the solution should be. Disable the installation button, add logic for fetching vacant ports, remove the starting the service from installer and keep the default values even though it will crash when started or leave it be for the remainder days of the Installers life cycle. What do you think?

**Comment by mmnosek** [comment]
I think we should do two things:
- add logic to check if ports are available at the beginning of installation (and proper alert/message in installation window)
- If this is the case, allow to install, do not rollback the whole installation but just show proper alert on service start

That would be ideal from my point of view.

**Comment by mmnosek** [comment]
But maybe we should ask the broader audience?

**Comment by ubbeK** [comment]
> But maybe we should ask the broader audience?

I think so.

> Ok, thanks for the investigation. I am not quiet sure in what the solution should be. Disable the installation button, add logic for fetching vacant ports, remove the starting the service from installer and keep the default values even though it will crash when started or leave it be for the remainder days of the Installers life cycle. What do you think?

> I think we should do two things:
> 
> add logic to check if ports are available at the beginning of installation (and proper alert/message in installation window)
> If this is the case, allow to install, do not rollback the whole installation but just show proper alert on service start
> That would be ideal from my point of view.

@alemoi @miyconst  @warpech  @joozek78  @Mackiovello  Any thoughts?

**Comment by miyconst** [comment]
>add logic to check if ports are available at the beginning of installation (and proper alert/message in installation window)
If this is the case, allow to install, do not rollback the whole installation but just show proper alert on service start

Agree on this.

>... but just show proper alert on service start

This is outside of installer, so might something that @ubbeK can not fix. Let's for now implement the installer alert at least.

**Comment by ubbeK** [comment]
This functionality that we speak of is actually already implemented.

![port_unavailable](https://user-images.githubusercontent.com/8124023/30070151-dea23a3e-9262-11e7-896a-2bcfa2dc64c3.gif)

Just run this program and then run the installer. It won't allow you to click install unless the port is changed. 

```c#
static void Main(string[] args)
{
    IPAddress ipAddress = IPAddress.Parse("127.0.0.1");
    try
    {
        TcpListener tcpListener = new TcpListener(ipAddress, 8181);
        tcpListener.Start();
    }
    catch (SocketException ex)
    {
        return;
    }

    while(true)
    {
        // infinit loop
    }
}
```
I also tried to install when port `8080` was blocket and it works fine.

The error from above is when we try to execute the newly created service `StarcounterSystemService`.  but I cannot reproduce it.

**Comment by ubbeK** [comment]
This is only reproducible when the Installer has been started, and THEN the port gets unavailable before clicking the Install button. At startup it creates a long list on invalid/taken ports so this is how @mmnosek must have done it. In order to be fully bullet proof of this we need the update and check that list again before starting the service.

**Comment by mmnosek** [comment]
No way! :) I've tested it for real. And now I've tested it once again with the newest RC (2.3.1.7119). Sorry for confusing - you should use "production" mode to see actual rollback.

If installed in developer mode, then works fine even if 8080 is taken (but it doesn't ask me to change anything). Try in production mode when 8080 is taken. Then it will fail as described above. It's really confusing that if my 8080 or 8181 port is not free and I choose:
1. Developer mode - it installs fine without any warning
2. Developer mode with additional options - it doesn't allow me to click next (but warns me)
3. Production mode - it will fail at the and rollback
4. Production mode with additional options - it doesn't allow me to click next (but warns me)

It's not constant that port is taken or not and installation success should not be dependant on this. So to be crystal clear, *in all 4 cases* we should allow installing, but warn user somehow. Are we all on the same page @miyconst @ubbeK ?

**Comment by ubbeK** [comment]
Ok,

I committed a change now that a warning message is shown if `Starcounter server service` fails to start and the Installation completes (does not rollback).  After this change I cannot reproduce this issue anymore. But then again, I did not test it on `Windows Server 2012 R2`, only on `Windows 10`.

**Comment by ubbeK** [comment]
@mmnosek May I close this issue?

**Comment by mmnosek** [comment]
Is it available to check already?

**Comment by ubbeK** [comment]
Tomorrow. I guess it is too late to start a build now.

**Comment by mmnosek** [comment]
Ok, I've checked latest build. Now it doesn't rollback installation (so initial issue is solved), but for me, it isn't perfect.

It should allow installing regardless of ports status. Just warn the user. If I choose "Change additional options" it is still not possible to install. But it's up to you. If you decide it's fine to have different behaviors in different installation options I'm fine with it and we can close :)

**Comment by ubbeK** [comment]
The only difference between `Developer` vs `Production` mode is how the `StarcounterServerService` is started, `manual` vs `auto` respectively. 

> If you decide it's fine to have different behaviors in different installation options I'm fine with it and we can close :)

I can never install when the `SystemHttpPort` is occupied regardless of `Developer`/`Production` mode. I am considering to add a `Skip port check`-checkbox in `Options`. @mmnosek What do you think? This should be enough right?

**Comment by ubbeK** [comment]
An `enable installation` checkbox has been added, which enables the `Install` button regardless if checks are failing or not.

Closing issue
