### ISSUE TITLE
Error : Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by iliasadfenix** [Starcounter/Home#270]
We are experiencing a new issue after upgrading SC version to 2.3.1.7294. Suddenly my code bellow start throwing error randomly. 

`info.Products.Data = ad.IndividualSeller.Customer.CustomerProducts.Where(p => p.IsSocialBooster == false);`

Here is the definition of `QueryResultRows<Product> CustomerProducts`  which is returning rows from database.

Here is the error:

![scerror](https://user-images.githubusercontent.com/28597134/31377994-ba84f3a6-adcb-11e7-8186-8252c7f848c7.PNG)

**Comment by k-rus** [comment]
Thank you for reporting this issue. This problem unfortunately exists for some time and @alemoi is expected to look at it.

**Comment by nazmuladfenix** [comment]
Sometimes I am getting the same exception even if I don't use any where clause

**Comment by alemoi** [comment]
Removed `CodeGenFilterCacheShared` because of faulty behavior and not much of a benefit, which should solve the issue. Thanks for reporting @nazmuladfenix !

**Comment by atifwaqar** [comment]
@bigwad 
This is a response to your comment on the wrong issue (My bad, I initiated it :P)
So, when you say it may be a coincidence, maybe you are right, but its weird that every time we get this bug and if we put a `?` the bug disappears. 

Also, do you think we can reopen this issue if but that I am facing right now falls under this issue?

**Comment by bigwad** [comment]
This issue was fixed this night as I see. Not sure corresponding build even has been built.

**Comment by atifwaqar** [comment]
Ah, this sounds great. 
let me know when you guys make the build, I can test at my end.

**Comment by alemoi** [comment]
@atifwaqar I suppose you can test with latest nightly now.

**Comment by atifwaqar** [comment]
@alemoi Looks like the problem is still there :( 

![image](https://user-images.githubusercontent.com/4388707/32495575-80f2e132-c3c6-11e7-830a-ff885130cd2f.png)

I'm using SC Version 2.3.1.7717

**Comment by alemoi** [comment]
> @alemoi Looks like the problem is still there :(

According to stack trace its a totally different issue. Its on different type of execution (IndexScan) and is not related to this issue.

@atifwaqar please create a new issue for this. Thanks!

**Comment by atifwaqar** [comment]
@alemoi Sure. I'm on it. :)
